# Main configuration file for AI Eye Tracking project

project:
  name: "ai-eye-tracking"
  version: "0.1.0"
  description: "Dyslexia detection via eye-tracking analysis"

data:
  raw_dir: "data/raw"
  interim_dir: "data/interim"
  processed_dir: "data/processed"
  batch_size: 32
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

model:
  encoder:
    input_dim: 128
    hidden_dim: 64
    output_dim: 32
    num_layers: 2
    dropout: 0.1
  
training:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler: "cosine"
  early_stopping_patience: 10
  
logging:
  log_dir: "logs"
  log_level: "INFO"
  tensorboard: true
  wandb: false
  checkpoint_dir: "models"
  
inference:
  model_path: "models/best_model.pt"
  batch_size: 64
  device: "cuda"  # or "cpu"
